@startuml

    interface DetectedTestObjectType [[DetectedTestObjectType.html]] {
        {abstract} +enrichAndNormalize(TestObjectDto): void
        {abstract} +getNormalizedResource(): Resource
        {abstract} +toTestObjectTypeDto(): TestObjectTypeDto
    }

@enduml
