@startuml

    class CredentialDto [[CredentialDto.html]] {
        +CredentialDto()
        +getApplicableTo(): ModelItemDto
        +setApplicableTo(ModelItemDto): void
        +getApplicableUri(): String
        +setApplicableUri(String): void
        +getCipher(): byte[]
        +setCipher(byte[]): void
        +createCopy(): CredentialDto
    }

@enduml
