@startuml

    class ResultStyleDto [[ResultStyleDto.html]] {
        #resource: URI
        +ResultStyleDto()
        +getResource(): URI
        +setResource(URI): void
        +createCopy(): ResultStyleDto
    }

@enduml
