== About ETF

ETF is an open source testing framework for validating spatial data, metadata and web services in Spatial Data Infrastructures (SDIs).

The design of ETF is driven by three goals: be user-friendly, consistency with the standards and the capability to test all resources in an SDI.

User-friendly means that you do not have to be a developer to use it and that test reports include sufficient information for technical staff to understand the reasons for warnings and errors detected during the execution of tests. The user interface and the test reports support multiple languages, too.

The concepts in ETF are based on ISO 19105 and the OGC Specification Model which underpin the standards used in SDIs. Tests are organized in Executable Test Suites, which may be developed and executed using different tools to properly support all kinds of resources in an SDI. Currently supported are:

* link:http://soapui.org/[SoapUI], a widely used tool for testing web services
* link:http://basex.org/[BaseX], an XML database, for testing sets of XML documents - including very large ones
* link:http://opengeospatial.github.io/teamengine[TEAM Engine], the tool used by the OGC CITE tests, to support the modern CITE tests developed using TestNG

ETF can be used via a responsive web application or via a REST API.

The easiest way to deploy ETF is a Docker container, available on Docker Hub.

The source code is published under the Apache 2.0 License.

link:http://www.interactive-instruments.de/[interactive instruments] has developed ETF and is the primary maintainer of the software.
