@startuml

    class MutableCachedRemoteResource [[MutableCachedRemoteResource.html]] {
        +setQueyParameters(Map<String, String>): boolean
        +createCopy(): MutableCachedRemoteResource
    }

@enduml
