@startuml

    class MutableSecuredRemoteResource [[MutableSecuredRemoteResource.html]] {
        +setQueyParameters(Map<String, String>): boolean
        +createCopy(): MutableSecuredRemoteResource
    }

@enduml
