@startuml

    interface ExecutableTestSuiteLifeCycleListener [[ExecutableTestSuiteLifeCycleListener.html]] {
        {abstract} +lifeCycleChange(Object, ExecutableTestSuiteLifeCycleListener.EventType, EidHolderMap<ExecutableTestSuiteDto>): void
    }

@enduml
