@startuml

    interface ExecutableTestSuiteLifeCycleListenerMediator [[ExecutableTestSuiteLifeCycleListenerMediator.html]] {
        {abstract} +registerListener(ExecutableTestSuiteLifeCycleListener): void
        {abstract} +deregisterListener(ExecutableTestSuiteLifeCycleListener): void
    }

@enduml
