@startuml

    class ExecutableTestSuiteUnavailable [[ExecutableTestSuiteUnavailable.html]] {
        +ExecutableTestSuiteUnavailable(ExecutableTestSuiteDto)
        +ExecutableTestSuiteUnavailable(ExecutableTestSuiteDto, Throwable)
        +ExecutableTestSuiteUnavailable(String)
    }

@enduml
