@startuml

    interface TestDriverManager [[TestDriverManager.html]] {
        +createTestRun(TestRunDto): TestRun
        {static} +getDefault(): TestDriverManager
        {abstract} +createTestRun(TestRunDto, TestResultCollectorFactory): TestRun
        {abstract} +setLoadingContext(LoadingContext): void
        {abstract} +getTestDriverInfo(): List<ComponentInfo>
        {abstract} +loadAll(): void
        {abstract} +load(EID): void
        {abstract} +unload(EID): void
        {abstract} +reload(EID): void
    }

@enduml
