@startuml

    class TestTaskInitializationException [[TestTaskInitializationException.html]] {
        +TestTaskInitializationException(Throwable)
        +TestTaskInitializationException(String, Throwable)
    }

@enduml
