@startuml

    interface TestRunLogReader [[TestRunLogReader.html]] {
        {abstract} +getLogFile(): File
        {abstract} +getLogMessages(long): List<String>
        {abstract} +streamLogMessagesTo(long, OutputStream): void
    }

@enduml
