@startuml

    class TestRunInitializationException [[TestRunInitializationException.html]] {
        +TestRunInitializationException(Throwable)
        +TestRunInitializationException(String, Throwable)
    }

@enduml
