@startuml

    interface ItemFileLoaderFactory.FileChangeListener [[ItemFileLoaderFactory.FileChangeListener.html]] {
        {abstract} +eventFileCreated(): void
        {abstract} +eventFileDeleted(): void
        {abstract} +eventFileUpdated(): void
    }

@enduml
