@startuml

    interface LoadingContext [[LoadingContext.html]] {
        {abstract} +getItemRegistry(): ItemRegistry
        {abstract} +getItemFileObserverRegistry(): ItemFileObserverRegistry
    }

@enduml
