== Installation on Linux

=== Prerequisites on Linux:
* Machine with at least 4 GB Ram (8GB are recommended, 16 GB and more if a large set of XML files are tested)
* link:https://www.java.com/en/download/help/linux_x64_install.xml[Oracle Java 8 is installed]
* link:https://tomcat.apache.org/download-80.cgi[Apache Tomcat 8 installed and configured]

=== Configure Tomcat on Linux
Tomcat 8 must be run with UTF-8 file encoding and two parameters must be set. The
parameters can be set in the *setenv.sh* file which is located in the *bin*
subfolder of the Tomcat application directory.

NOTE: The Tomcat application directory is Linux distribution specific. In some
distributions it is located at */opt/tomcat/*.

The following lines must be added to the setenv.sh file:
[source,bash]
----
export JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8 -Djavax.servlet.request.encoding=UTF-8"
----

Restart Tomcat afterwards.

=== Install ETF web application on Linux

. Download the link:https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive_instruments/etf/etf-webapp/2.0.0/etf-webapp-2.0.0.war[latest ETF-Webapp] version, using etf-public-dev as user and password.
. Rename the etf-webapp-2.x.x.war file to etf-webapp.war . Otherwise, the version must be specified in the URL after the deployment.
. Either copy the etf-webapp.war file to *TOMCAT_INSTALLATION_DIRECTORY/webapps* or deploy the file using the Tomcat manager. If the manager is used, make sure that **max-file-size** and **max-request-size** are set to at least 157286400 (150 Megabytes) in the *TOMCAT_INSTALLATION_DIRECTORY/webapps/manager/WEB-INF/web.xml* file:
+
[source,xml]
----
    <multipart-config>
      <!-- 150MB max -->
      <max-file-size>157286400</max-file-size>
      <max-request-size>157286400</max-request-size>
      <file-size-threshold>0</file-size-threshold>
    </multipart-config>
----
. The application will start and initially create the ETF directory structure in the directory *~/.etf* (note: the directory is hidden). If the environment variables TOMCAT_HOME or CATALINA_HOME are set the etf.log file is stored in *$TOMCAT_HOME/logs/etf.log* or *$CATALINA_HOME/logs/etf.log* otherwise in *~/.etf/logs/etf.log*
. Download the link:https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive_instruments/etf/bsxm/etf-gmlgeox/1.1.0/etf-gmlgeox-1.1.0.jar[latest GmlGeoX library]. Rename the downloaded file to GmlGeoX.jar (note: the file name is case-sensitive). Afterwards copy the file to *~/.etf/ds/db/repo/de/interactive_instruments/etf/bsxm*.
. Download <<ets-installation>> and extract archives into the *~/.etf/projects* directory. The web application will automatically load the Executable Test Suites after a few seconds.
. The web application can be accessed via link:http://localhost:8080/etf-webapp[http://localhost:8080/etf-webapp].
If ETF is accessed not only from one local machine, the *etf.webapp.base.url* property must be changed in the <<etf-configuration-dir>> to your server address (e.g. http://etf-server:8080/etf-webapp).
. Check the <<etf-log-file>> file for errors.
