
CAUTION: not implemented and published yet

== Identifying model items

There are two types that can be used to identify a model item in ETF.

Every model item must provide an unique *EID* and can optionally possess an
*EGAID*.

=== EID
The EID (ETF ID) is a hexadecimal Universally Unique Identifier prefixed with
'EID', for instance:
----
EID12bb90ca-ee02-4f79-9dd9-63dff6d8e150
----
NOTE: Since the type is unique a collection shall not contain multiple items with the same ETFID!

=== EGAID
The EGAID (ETF Group and Artifact Id) syntax is based on the Java package syntax and provides an identifier for one model item in different versions.

NOTE: Since the EID must be unique, the EID for a new version of a model item must
be different.

All charachters in the EGAID must be lower-case and must not contain
special-characters except the dot, for instance:
----
eu.inspire.validation.ets.downloadservices.atompredefined
----

The EGAID is not unique and a collection of model items may contain multiple
items with the same EGAID.

=== Referencing model items

==== EID reference
The EID reference *ref* can be used to reference model items by their EID. The reference can be an absolute or a relative URI.

The absoulute URI syntax consists of the service URL, a type specific part and the EID. Example:
----
http://etf/v2/ExecutableTestSuites/EID12bb90ca-ee02-4f79-9dd9-63dff6d8e150
----

NOTE: The framework accepts EIDs that are not prefixed with 'EID'. This may change in future versions.

If a model item is referenced from within an item collection, the relative URI syntax is used. Example in XML:
----
<testObject xsi:type="loc" ref="EID2eee5bf8-7d1a-489b-ab73-a5b86688a421"/>
----

Example in JSON:
----
"testObject": {"ref": "EID2eee5bf8-7d1a-489b-ab73-a5b86688a421"},
----


==== Version specific reference

The *egaref* is an URI used to reference ETF model items by their EGAID and version.
The URI must be absolute. The URI consists of the service URL, a type specific part, the EGAID, a colon and the version. Example, for referencing an Executable Test Suite in version
1.0.1:
----
http://etf/v2/ExecutableTestSuites/eu.inspire.validation.ets.downloadservices.atompredefined:1.0.1
----
