== Information and concepts used by all Executable Test Suites

=== Overview

All Executable Test Suites can make use of and reference generic information items that is used by ETF to organize Executable Test Suites and present test reports to a user.

How these items are referenced in the different types of Executable Test Suites is described in the section for each test engine.

These items are:

* Collections of multi-lingual message templates for use in test reports for one or more Executable Test Suites
* Tags that may be associated with an Executable Test Suite to support grouping and filtering

These items that stored as XML documents in the  `include-metadata`
directory of an ETF deployment (see the link:http://docs.etf-validator.net/Admin_manuals/index.html#_etf_data_directory_structure[description of the ETF directory structure]).

include::Translation_Template.adoc[]

include::Tag.adoc[]

[[test-object-types]]
=== Test object types

A Test Object Type is a classification of a test object. Every Executable Test Suite in ETF declares which types of test objects it supports. This allows to determine which Executable Test Suites may be included in a test run against a test object. Test object types are structured in a hierarchical vocabulary.

The Test Object Types are used to check whether two or more Executable Test Suites can be executed on the same test object together in one Test Run.

Every test engine supports one or more Test Object Types. The types supported by each test engine are described in the section on the test engines (link:#basex-test-object-types[BaseX], link:#soapui-test-object-types[SoapUI]). For the TEAM Engine, the applicable types from the other test engines are specified for link:#te-test-suites[each TEAM Engine test suite].

[[test-item-types]]
=== Test item types

Each test step and test assertion is classified depending on the characteristics of the item. As the classification depends on the test engine, the pre-defined test item types for each test engine are specified in the section of the test engine (link:#basex-test-item-types[BaseX], link:#soapui-test-ietm-types[SoapUI]). For the TEAM Engine internal test item types are created, but these are not visible to test developers.

[[attachments]]
=== Attachments

Additional files may be "attached" to a test result. These includes log files, statistical information, service requests and responses, etc. The attachments are linked from or embeded in the test reports in HTML to provide additional information about the test run.

The details depend on the test engine and the attachments that may occur for each test engine and are documented in the section of the test engine (link:#basex-attachments[BaseX], link:#soapui-attachments[SoapUI], link:#te-attachments[TEAM Engine]).
