=== Development environment

A SoapUI Executable Test Suite is developed and tested using the
SoapUI GUI application.

==== Installation

Prerequisites for the following steps to set up the ETS development environment are:

* Windows OS (it may work on Linux, too, but it is known to not work under macOS)
* Java 1.8
* SoapUI 5.3.0 installed

Then follow these steps under Windows:

1. Download link:https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive_instruments/etf/suim/SoapUI-ETF.zip[this ZIP file] (using "etf-public-dev" as username and password)
1. Extract the ZIP file in any directory
1. Run 'install-plugins.bat'
1. Run 'SoapUI 5.3.0.bat'

To load the plugins, SoapUI must always be started with the 'SoapUI 5.3.0.bat' file from the extracted directory.

NOTE: This procedure is required as link:https://github.com/SmartBear/soapui/pull/201[Smartbear decided to lock out unsigned plugins]. Because the signing process is not transparent to us, we decided to use this workaround.

==== Executing tests

#This is not understandable at this point. I have only set up the environment, but there is no SoapUI project yet, where I could set serviceEndpoint, etc. It is also unclear on which "Test project" I should double click and where.#

To execute a test suite against a web service set the serviceEndpoint property
and the username and password (authUser and authPwd properties) if the service
requires authentication.

Double click on the Test project, click on the 'Test Suites' tab and start the
test run with a click on the green arrow.

#Screenshot?#
