== TEAM-Engine-based test suites

=== Overview

Support for the TEAM Engine is different then for the other test engines.

While it would be possible to develop new test suites in the TEAM Engine, this is not recommended as the TEAM Engine does not support many aspects of the ETF information model.

NOTE: This link:http://opengeospatial.github.io/teamengine/testng-essentials.html[manual] has information for developing test suites for the Team Engine.

The TEAM Engine is primarily supported by ETF to allow that "native" Executable Test Suites for the test engines BaseX and SoapUI can declare dependencies to test suites developed for the TEAM Engine and so that ETF can execute these test suites using a remote TEAM Engine instance, typically the one hosted by OGC for their Compliance Program (CITE).

The test results reported by the TEAM Engine are transformed by ETF into the model of ETF for test results.

=== TEAM Engine test suites supported by ETF

Test suites for the TEAM Engine may be written in CTL or TestNG.

A TEAM Engine test suite may be used in ETF, if it meets the following requirements:

* The test suite has been developed in TestNG (most recent and all new test suites are planned to be developed using TestNG).
* The test suite can be invoked using a link:http://cite.opengeospatial.org/teamengine/rest/suites[simple REST API].
* The test suite accepts the same test objects as the ETF test suite (the OGC CITE WFS 2.0 test accepts a WFS 2.0 URL, which is also a well-known ETF Test Object Type; however, the OGC CITE GML 3.2 test accepts a URL of the single GML file whereas ETF accepts also multiple files in a ZIP archive as well as data upload instead of a public URL)

TEAM Engine test suites that are currently registered in ETF as Executable Test Suite are listed in the following table:

[[te-test-suites]]
.TEAM Engine test suites registered in ETF
[width="100%",options="header",cols="1,3,3,1"]
|===
|  *Test suite* | *ID in ETF* | *Supported ETF Test Object Types* | *URL*
| WFS 2.0 | EID95a1b6fc-2b55-3d43-9502-3b8b605bda10 | link:#soapui-test-object-types[OGC Web Feature Service 2.0] | link:http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/[Link]
|===

The ID must be used in other Executable Test Suites to establish a dependency to a TEAM Engine test suite.

The TEAM Engine test suite is associated with a pre-defined link:#tags[Tag]:

[source,XML]
----
<etf:Tag id="EID268af871-5cf0-443e-834a-ce40bed6c0e3">
  <label>OGC Test Suites (remote execution)</label>
  <description>Executable Test Suites that are executed on a remote OGC TEAM Engine instance</description>
  <priority>1000</priority>
</etf:Tag>
----

ETF currently does not support any CTL-based tests, which return test results in a different XML structure.

WARNING: One pre-condition for using an OGC CITE test suite is that it does not require pre-loading any data into the service under test. For older tests (for example, the WMS 1.x and WFS 1.x test suites) loading a pre-defined test dataset was a typical requirement. Those OGC CITE test suites may only be used to test a resource that uses the test data.

NOTE: In the future, it is planned to harmonize the XML format of all TEAM Engine test results using W3C EARL. Once that has been implemented - and ETF supports the EARL-based result format - also CTL-based test suites should be usable as long as they do not require any pre-loaded data and are accessible via the simple API.

=== Mapping from TEAM Engine / TestNG concepts to ETF

#JFH: Explain rules how the results are mapped.#

WARNING: Some information that is typically included in ETF test results is not included in the TEAM Engine reports and, therefore, cannot be included in the ETF test reports.

[[te-attachments]]
=== Attachments

#JFH: describe attachments that are referenced from TEAM Engine test results and their types.#
