[[message-template-bundles]]
=== Message template bundles

Message templates are collected in an XML document with a root element
`etf:TranslationTemplateBundle`. The file name must start with the
prefix "TranslationTemplateBundle" and must be located in the directory
`include-metadata`. The `id` attribute must be a unique UUID, prefixed with "EID".

TIP: https://github.com/interactive-instruments/etf-ets-repository/blob/master/generic/include-metadata/generic-ettb.xml[generic-ettb.xml]
can be used as a starting point for a translation template bundle. Do
not forget to change the `id` attribute to a different UUID.

.Message templates used for Executable Test Suites in INSPIRE
=====================================================================
The template bundle for the BaseX-based tests in the INSPIRE validator is
https://github.com/inspire-eu-validation/ets-repository/blob/master/include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml[TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml].

The template bundle for the SoapUI-based tests in the INSPIRE validator is
https://github.com/inspire-eu-validation/ets-repository/blob/master/include-metadata/TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml[TranslationTemplateBundle-EIDfadd4929-fa60-4781-b658-703bbfe3f4eb.xml].
=====================================================================

Each message template is in an `etf:LangTranslationTemplateCollection`
element and includes an `etf:TranslationTemplate` per language for the
same message. The language is encoded in the `language` attribute using
language codes used in HTTP headers, e.g. "en" for English.

The placeholders are embedded in curly brackets, e.g. "\{filename}".

IMPORTANT: All names must start with "TR." and may only use the following characters: #add list of characters#.

IMPORTANT: The `name` attribute values of an `etf:LangTranslationTemplateCollection` element and its `etf:TranslationTemplate` elements must be identical.

.A single message template in two languages
=====================================================================
[source,XML]
----
<TranslationTemplateBundle xmlns="http://www.interactive-instruments.de/etf/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.interactive-instruments.de/etf/2.0 http://resources.etf-validator.net/schema/v2/model/resultSet.xsd"
   id="EID27117afb-11aa-4e45-aa3d-0e1e65bdccb8">
    <translationTemplateCollections>
      <LangTranslationTemplateCollection name="TR.incorrectRoot">
         <translationTemplates>
            <TranslationTemplate language="en" name="TR.incorrectRoot">XML document '{filename}': The root element is not one of the recognised feature collections: wfs:FeatureCollection (WFS 1.1 or WFS 2.0) or gml:FeatureCollection (GML 3.1 or GML 3.2). The name of the root element is '{elementName}' in namespace '{namespace}'.</TranslationTemplate>
            <TranslationTemplate language="de" name="TR.incorrectRoot">XML-Dokument '{filename}': Das Wurzelelement ist keines der erwarteten Feature-Collection-Elemente: wfs:FeatureCollection (WFS 1.1 oder WFS 2.0) oder gml:FeatureCollection (GML 3.1 oder GML 3.2). Der Name des Wurzelelements is '{elementName}' im Namensraum '{namespace}'.</TranslationTemplate>
         </translationTemplates>
      </LangTranslationTemplateCollection>
    </translationTemplateCollections>
</TranslationTemplateBundle>
----
=====================================================================
