:doctype: book

:stylesdir: ../stylesheets/
:stylesheet: etf.css
:linkcss:

:toc: macro
:toc-title: Table of contents
:toclevels: 2
:toc-position: left
:appendix-caption: Annex

:icons: font

:source-highlighter: pygments
:pygments-style: autumn
:pygments-linenums-mode: inline

include::../General/Logo.adoc[]

:doc-warning-work-in-progress: false
:doc-title: Web API v2
:doc-status: in review
:doc-date: 2017-06-21
:doc-description: Quickstart manual for the 2nd version of the ETF Web API. For the complete documentation of the API, consult the Swagger documentation.
:doc-audience: Developers planning to use the ETF Web API v2 to automate test runs with an ETF instance, for example in an automated test pipeline.
:doc-id: http://docs.etf-validator.net/Developer_manuals/WEB-API.html
:doc-lang: EN

include::../General/Document-metadata.adoc[]

== Changelog
[width="100%",options="header",cols="1,2,3"]
|===
|  *Date* | *Editor* | *Comments*
| 2017-04-24 | Jon Herrmann | document converted from GitHub wiki
| 2017-06-21 | Clemens Portele | editorial updates
|===

<<<

toc::[]

<<<

include::../General/About-short.adoc[]

== Overview

The ETF Web API v2 is used to retrieve Framework metadata, start/observe/manage tests and retrieve test results.

The API is published and documented in detail as a Swagger definition on link:https://app.swaggerhub.com/api/etf/etf/[Swaggerhub]. The ETF web application instance also provides the Swagger web interface which is available at

----
http://your-etf-server/path/swagger-ui.html
----

.Retrieving all installed Executable Test Suites in JSON
=====================================================================
----
http://your-etf-server/path/v2/ExecutableTestSuites.json
----
=====================================================================

== Response schema model
The response model is based on a XML schema. The interactive XML schema documentation is available link:http://resources.etf-validator.net/schema/v2/doc/service.html[here]. Since the JSON responses are transformed from the XML, they are also based on this schema.

== Starting a Test Run with the API
First the ID of the Executable Test Suite that shall be used needs to be known. All available Executable Test Suites can be queried by invoking the GET request (replace localhost:8080 with your server address):
----
http://localhost:8080/v2/ExecutableTestSuites.json
----

The response may look like this (excerpt):
[source,JSON]
----
{
	"EtfItemCollection": {
		"returnedItems": 51,
		"position": 0,
		"ref": "http://localhost:8080/v2/ExecutableTestSuites.json",
		"executableTestSuites": {
			"ExecutableTestSuite": [{
					"id": "EIDec7323d5-d8f0-4cfe-b23a-b826df86d58c",
					"remoteResource": "https://github.com/inspire-eu-validation/ets-repository/tree/master/metadata/iso",
					"label": "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119",
					...
					"ParameterList": {
						"name": "ETF Standard Parameters for metadata XML test objects",
						"parameter": [{
							"name": "tests_to_execute",
							"required": false,
							"defaultValue": ".*",
							"description": {
								"ref": "TR.testsToExecute"
							},
							"allowedValues": ".*",
							"type": "string"
						}, {
							"name": "files_to_test",
							"required": true,
							"defaultValue": ".*",
							"description": {
								"ref": "TR.filesToTest"
							},
							"allowedValues": ".*",
							"type": "string"
						}]
					},
					...
				}
			}
----

In this example the Executable Test Suite **Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119** with the **EIDec7323d5-d8f0-4cfe-b23a-b826df86d58c** is used.
To start a new Test Run with test data that are located at http://example.com/test-data.zip a JSON request must be send via POST to the interface:
----
http://localhost:8080/v2/TestRuns
----
The example testRunRequest JSON object may look like this:
[source,JSON]
----
{
  "label": "Test run on 15:00 - 01.01.2017 with Conformance class INSPIRE Profile based on EN ISO 19115 and EN ISO 19119",
  "executableTestSuiteIds": ["EIDec7323d5-d8f0-4cfe-b23a-b826df86d58c"],
  "arguments": {
    "files_to_test": ".*",
    "tests_to_execute": ".*"
  },
  "testObject": {
    "resources": {
			"data": "http://example.com/test-data.zip"
    }
  }
}
----

In this example the resource ID needs to be set to **data**, for file based resources. If a service is tested, the resource ID needs to be set to **serviceEndpoint**:
[source,JSON]
----
{
  ...,
  "testObject": {
    "resources": {
      "serviceEndpoint": "http://example.com/service?SERVICE=WFS&REQUEST=GetCapabilities"
    }
  }
}
----

On success a Test Run object will be returned as JSON.
Example:
[source,JSON]
----
{
  "EtfItemCollection": {
    "returnedItems": 1,
    "ref": "http://localhost:8080/v2/TestRuns/1dfbed0e-131e-489d-a0a4-712f4259c30a.json",
    "testRuns": {
      "TestRun": {
        "id": "EID1dfbed0e-131e-489d-a0a4-712f4259c30a",
        "label": "Test run on 15:00 - 01.01.2017 with test suite Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119",
        "defaultLang": "en",
        "startTimestamp": "2017-01-01T15:00:00.000+01:00",
        "testTasks": {
          "TestTask": [
            {
              "id": "EIDe8714e65-d435-458f-9cf8-5f912adde0e3",
              "parent": {
                "ref": "EID1dfbed0e-131e-489d-a0a4-712f4259c30a"
              },
              "executableTestSuite": {
                "ref": "EIDe3500038-e37c-4dcf-806c-6bc82d585b3b"
              },
              "testObject": {
                "ref": "EIDeb5c79c8-5be8-4029-83e4-5cf0cde5d33c"
              },
              ...
}
----

The returned ID - in this example **EID1dfbed0e-131e-489d-a0a4-712f4259c30a** - can then be used to monitor the progress by invoking the interface :
----
http://localhost:8080/v2/TestRuns/EID1dfbed0e-131e-489d-a0a4-712f4259c30a/progress
----
which will return a Progress Object:

[source,JSON]
----
{
  "val": "30",
  "max": "30",
  "log": []
}
----

As the val property equals the max property, the test run already finished and the HTML report can be fetched by invoking
----
http://localhost:8080/v2/TestRuns/EID1dfbed0e-131e-489d-a0a4-712f4259c30a.html
----
